PANDAS

In [1]:
import pandas as pd

#Series

In [2]:
my_list = [26,78,56,46,22]

In [3]:
z = pd.Series(data=my_list)
z

0    26
1    78
2    56
3    46
4    22
dtype: int64

In [4]:
type(z)

pandas.Series

In [5]:
z =pd.Series(my_list,index=['A','B','C','D','E'])
z

A    26
B    78
C    56
D    46
E    22
dtype: int64

In [6]:
z['E']

np.int64(22)

In [7]:
pd.__version__

'3.0.2'

In [8]:
p = pd.Series(data=my_list)
p

0    26
1    78
2    56
3    46
4    22
dtype: int64

In [9]:
p[4]

np.int64(22)

In [11]:
z['E']

np.int64(22)

In [12]:
cricket = {"captain":"virat","opener":"rohit","keeper":"dhoni"}
cricket

{'captain': 'virat', 'opener': 'rohit', 'keeper': 'dhoni'}

In [13]:
sample  =pd.Series(cricket)
sample

captain    virat
opener     rohit
keeper     dhoni
dtype: str

In [14]:
sample['captain']

'virat'

In [15]:
ser = pd.Series([1,2,3,4],["USA","Germany","USSR","Japan"])
ser

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [16]:
ser2 = pd.Series([5,6,7,9],["USA","Germany","Italy","Japan"])
ser2

USA        5
Germany    6
Italy      7
Japan      9
dtype: int64

In [17]:
ser + ser2

Germany     8.0
Italy       NaN
Japan      13.0
USA         6.0
USSR        NaN
dtype: float64

#DataFrames

In [18]:
Sam_dict = {"Empcode":[1,2,3,4],"Name":["Surya","Akhil","Rishi","Anusha"],"Occupation":["ML Developer","Manager","BI Developer","AI Engineer"],
            "Date of Join":["2025-01-01","2024-03-03","2023-03-04","2020-04-09"]}
employees = pd.DataFrame(Sam_dict)
employees

   Empcode    Name    Occupation Date of Join
0        1   Surya  ML Developer   2025-01-01
1        2   Akhil       Manager   2024-03-03
2        3   Rishi  BI Developer   2023-03-04
3        4  Anusha   AI Engineer   2020-04-09

In [19]:
type(employees)

pandas.DataFrame

In [ ]:
Sample_dict = {"Empcode":[1,2,3,4],"Name":["Surya","Akhil","Rishi","Anusha"],"Occupation":["ML Developer","Manager","BI Developer","AI Engineer"],
            "Date of Join":["2025-01-01","2024-03-03","2023-03-04"]}
employees_test = pd.DataFrame(Sample_dict)
employees_test

ValueError: All arrays must be of the same length

In [21]:
employees

   Empcode    Name    Occupation Date of Join
0        1   Surya  ML Developer   2025-01-01
1        2   Akhil       Manager   2024-03-03
2        3   Rishi  BI Developer   2023-03-04
3        4  Anusha   AI Engineer   2020-04-09

In [22]:
employees.columns

Index(['Empcode', 'Name', 'Occupation', 'Date of Join'], dtype='str')

In [23]:
employees.columns=['Empcode', 'EmpName', 'EmpOccupation', 'EmpDOJ']

In [24]:
employees

   Empcode EmpName EmpOccupation      EmpDOJ
0        1   Surya  ML Developer  2025-01-01
1        2   Akhil       Manager  2024-03-03
2        3   Rishi  BI Developer  2023-03-04
3        4  Anusha   AI Engineer  2020-04-09

In [25]:
employees.rename(columns={"Empcode":"EmpNo"})

   EmpNo EmpName EmpOccupation      EmpDOJ
0      1   Surya  ML Developer  2025-01-01
1      2   Akhil       Manager  2024-03-03
2      3   Rishi  BI Developer  2023-03-04
3      4  Anusha   AI Engineer  2020-04-09

In [26]:
employees

   Empcode EmpName EmpOccupation      EmpDOJ
0        1   Surya  ML Developer  2025-01-01
1        2   Akhil       Manager  2024-03-03
2        3   Rishi  BI Developer  2023-03-04
3        4  Anusha   AI Engineer  2020-04-09

In [27]:
employees.rename(columns={"Empcode":"EmpNo"},inplace=True)

In [28]:
employees

   EmpNo EmpName EmpOccupation      EmpDOJ
0      1   Surya  ML Developer  2025-01-01
1      2   Akhil       Manager  2024-03-03
2      3   Rishi  BI Developer  2023-03-04
3      4  Anusha   AI Engineer  2020-04-09

In [30]:
employees["EmpAge"]=[23,34,53,67]

In [31]:
employees

   EmpNo EmpName EmpOccupation      EmpDOJ  EmpAge
0      1   Surya  ML Developer  2025-01-01      23
1      2   Akhil       Manager  2024-03-03      34
2      3   Rishi  BI Developer  2023-03-04      53
3      4  Anusha   AI Engineer  2020-04-09      67

In [32]:
employees.drop("EmpNo",axis=1,inplace=True)
employees

  EmpName EmpOccupation      EmpDOJ  EmpAge
0   Surya  ML Developer  2025-01-01      23
1   Akhil       Manager  2024-03-03      34
2   Rishi  BI Developer  2023-03-04      53
3  Anusha   AI Engineer  2020-04-09      67

In [33]:
employees.columns

Index(['EmpName', 'EmpOccupation', 'EmpDOJ', 'EmpAge'], dtype='str')

In [42]:
employees.drop(employees.columns[[0,2]],axis=1)

  EmpOccupation  EmpAge
0  ML Developer      23
1       Manager      34
2  BI Developer      53
3   AI Engineer      67

In [43]:
employees

  EmpName EmpOccupation      EmpDOJ  EmpAge
0   Surya  ML Developer  2025-01-01      23
1   Akhil       Manager  2024-03-03      34
2   Rishi  BI Developer  2023-03-04      53
3  Anusha   AI Engineer  2020-04-09      67

In [45]:
employees.drop(3,axis=0)

  EmpName EmpOccupation      EmpDOJ  EmpAge
0   Surya  ML Developer  2025-01-01      23
1   Akhil       Manager  2024-03-03      34
2   Rishi  BI Developer  2023-03-04      53

In [46]:
employees

  EmpName EmpOccupation      EmpDOJ  EmpAge
0   Surya  ML Developer  2025-01-01      23
1   Akhil       Manager  2024-03-03      34
2   Rishi  BI Developer  2023-03-04      53
3  Anusha   AI Engineer  2020-04-09      67

In [47]:
employees.insert(loc=0,column="EmpSurname",value=["M","N","P","Q"])

In [48]:
employees

  EmpSurname EmpName EmpOccupation      EmpDOJ  EmpAge
0          M   Surya  ML Developer  2025-01-01      23
1          N   Akhil       Manager  2024-03-03      34
2          P   Rishi  BI Developer  2023-03-04      53
3          Q  Anusha   AI Engineer  2020-04-09      67

In [54]:
new = {"EmpSurname":"D",	"EmpName":"Ramesh"	,"EmpOccupation":"Sales",	"EmpDOJ":"2022-04-04",	"EmpAge":24}

In [52]:
employees.loc[4]=["B","Ram"	,"Sales","2022-04-04",24]

In [53]:
employees

  EmpSurname EmpName EmpOccupation      EmpDOJ  EmpAge
0          M   Surya  ML Developer  2025-01-01      23
1          N   Akhil       Manager  2024-03-03      34
2          P   Rishi  BI Developer  2023-03-04      53
3          Q  Anusha   AI Engineer  2020-04-09      67
4          B     Ram         Sales  2022-04-04      24

In [58]:
new

{'EmpSurname': 'D',
 'EmpName': 'Ramesh',
 'EmpOccupation': 'Sales',
 'EmpDOJ': '2022-04-04',
 'EmpAge': 24}

In [60]:
s= pd.DataFrame([new])
s

  EmpSurname EmpName EmpOccupation      EmpDOJ  EmpAge
0          D  Ramesh         Sales  2022-04-04      24

In [61]:
employees= pd.concat([employees,s],ignore_index=True)
employees

  EmpSurname EmpName EmpOccupation      EmpDOJ  EmpAge
0          M   Surya  ML Developer  2025-01-01      23
1          N   Akhil       Manager  2024-03-03      34
2          P   Rishi  BI Developer  2023-03-04      53
3          Q  Anusha   AI Engineer  2020-04-09      67
4          B     Ram         Sales  2022-04-04      24
5          D  Ramesh         Sales  2022-04-04      24